dynamic_HSV_server/H_min_L: 0
dynamic_HSV_server/H_max_L: 180
dynamic_HSV_server/S_min_L: 20
dynamic_HSV_server/S_max_L: 180
dynamic_HSV_server/V_min_L: 90
dynamic_HSV_server/V_max_L: 255

dynamic_HSV_server/H_min_R: 0
dynamic_HSV_server/H_max_R: 255
dynamic_HSV_server/S_min_R: 0
dynamic_HSV_server/S_max_R: 255
dynamic_HSV_server/V_min_R: 0
dynamic_HSV_server/V_max_R: 255



