dynamic_HSV_server/H_min_left: 10
dynamic_HSV_server/H_max_left: 50
dynamic_HSV_server/S_min_left: 20
dynamic_HSV_server/S_max_left: 255
dynamic_HSV_server/V_min_left: 170
dynamic_HSV_server/V_max_left: 255

dynamic_HSV_server/H_min_right: 10
dynamic_HSV_server/H_max_right: 50
dynamic_HSV_server/S_min_right: 20
dynamic_HSV_server/S_max_right: 255
dynamic_HSV_server/V_min_right: 170
dynamic_HSV_server/V_max_right: 255
